### ISSUE TITLE
KeyError: 'conversation_state'

### ISSUE THREAD

**Issue by snoopy-coder** [jacobmanning/hangouts-parser#1]
When I try to use your parser on a very large `Hangouts.json` (over 300 MB) through [bigjson](https://github.com/henu/bigjson) library, I get the following error:
```
C:\Temp\hangouts-parser-master>python parser.py
[ INFO ]:  Started script
[ INFO ]:  Parsing JSON file: raw/Hangouts.json
Traceback (most recent call last):
  File "parser.py", line 262, in <module>
    main(args.file_path)
  File "parser.py", line 244, in main
    for state in json_archive['conversation_state']:
  File "C:\Temp\python-3.7.1\Lib\site-packages\bigjson\obj.py", line 141, in __getitem__
    return self._get(key, None, Object._GET_METHOD_RAISE_EXCEPTION)
  File "C:\Temp\python-3.7.1\Lib\site-packages\bigjson\obj.py", line 192, in _get
    raise KeyError(key)
KeyError: 'conversation_state'
```
I guess a workaround is needed to avoid the situation, if the file does not contain `conversation_state` at all, as is done, for example, in [hangouts-log-reader](https://bitbucket.org/dotcs/hangouts-log-reader/issues/1/keyerror-conversation_state). 
How difficult is slightly modify the script? Thanks a lot.

**Comment by jacobmanning** [comment]
Hey! Sorry for the... very late... response 😂 Agreed with the conversation you linked that I was under the impression there would always be a `conversation_state`. Still, I can edit so we print a nicer error message rather than crashing

**Comment by jacobmanning** [comment]
Should be resolved now, closing. Lmk if it doesn't work and I'll try and fix it (maybe in less than a year this time 🙂 )
